### ISSUE TITLE
vector size serialization optimization

### ISSUE THREAD

**Issue by suemto** [mwcproject/mwc-node#25]
When going through this code snippet, I got an idea for a small optimization, maybe it is not a good idea but I want to collect some comments on it. 🌷 🚀 

(Look at the following code) Current transaction serialization is using `u64` for the vector size, which is 8 bytes, but also the vector size is limited with `READ_VEC_SIZE_LIMIT` which is `100_000` for all existing releases. May I suggest to change this as `u32` instead? This will save 12 bytes payload for the mwc transaction.

https://github.com/mwcproject/mwc-node/blob/4.1.0/core/src/core/transaction.rs#L527-L546

```Rust
		if self.inputs.len() > ser::READ_VEC_SIZE_LIMIT as usize
			|| self.outputs.len() > ser::READ_VEC_SIZE_LIMIT as usize
			|| self.kernels.len() > ser::READ_VEC_SIZE_LIMIT as usize
		{
			return Err(ser::Error::TooLargeWriteErr(format!(
				"Transaction has impossibly many items: inputs {}, outputs {}, kerners {}",
				self.inputs.len(),
				self.outputs.len(),
				self.kernels.len()
			)));
		}
		ser_multiwrite!(
			writer,
			[write_u64, self.inputs.len() as u64],
			[write_u64, self.outputs.len() as u64],
			[write_u64, self.kernels.len() as u64]
		);
```

The *drawbacks* of this optimization:
- This is a *Consensus Breaking* change. We can use next Hard Fork chance to integrate this change.
- For Mimblewimble, the whole chain can be looked as ONE transaction, a huge merged one! So, in any case a huge merged transaction is needed to be serialized, this will become a problem because it limits the vector size to 4.29 billion.

Using `u64` to encode a vector size here is a wasting or not❓

**Comment by bayk** [comment]
READ_VEC_SIZE_LIMIT  is a global constant, it is not a part of the payload.  
Sure you can change the type, but I don't see the impact. It is a constant and compiler will put a constant into generated code with needed type.

**Comment by suemto** [comment]
(To be updated for investigation of all vector serialization, and taking into account the backward compatibility.)
